### ISSUE TITLE
Discussion: The minimal features the IHM app should have to function

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Site#1087]
### Will allow me to move away from OruxMaps:

- [x] Offline maps #783
- [x] Auto-dimming #947

### Important but I can live without it:

1. Reliable track recording in the background #1039
2. Offline routing
3. Separation between followed route and recording #1080
4. Accurate height statistics #1076
5. Following a route and related features (off-route warning etc.) 
6. Offline POIs #783

### Will allow me to move away from OruxMaps:

- [x] Maintain reliable track recording when the app is in the background for a full day. #1039
- [x] Allow switching between North-up and Direction-up map orientation when following the GPS position or recording a track.  #1014
- [x] Require confirmation before a recording is stopped.  #1095 
- [x] The "Follow GPS" button should not stop a recording. When recording is active, it should enable/disable following the GPS and rotating the map (if applicable). #1096

Other requests may come up once the above is implemented and further real-life testing the IHM app is done.

### Will allow me to move away from OruxMaps:
- [x] Offline maps: #783
- [x] Offline POIs: #783
- [x] Track recording: #1039

### Nice-to-have:
1. Offline POIs Edit and sync when returning to online: #783 or a separate issue I'll open since this feature is too big.

**Comment by HarelM** [comment]
@valleyofdawn it is not clear from you description above what is the difference between essential and important.
Please use my terminology: what will allow you to move away from orux, the rest is nice to have. you can prioritize the nice to have in importance order. 
Please also link the relevant issues to each request line (can be seen in my example).

**Comment by valleyofdawn** [comment]
Since I don't know if background tracking would work anytime soon my only urgent wish is to make automatic screen-dimming and one-touch wake-up work #947.
The offline map and measurement work well enough for me but would have to work better for production.
**Explanation** (it's long so you don't have to read it):
It’s important to me to record the ride for 3 reasons:
1)	I want to know how much I’ve ridden to be able to plan ahead – I don’t want to ride too slow and reach sunset, nor exert myself with riding too fast and risk dehydrating.
2)	I want to immediately know which direction to go when I start riding after a stop, and my recorded path helps a lot with navigation at a glance when crossing your own path. 
3)	I want to show off the ride on social media after I finish.
As you know, track recording is stable in the foreground and crashes frequently in the background.
The way I’m dealing with this now is by **manually increasing and decreasing the screen brightness** – a complicated task with one hand while riding, especially when the screen is darkened and you can hardly see it to turn the light up again.
I tend to not fiddle with other apps on the phone while riding, so the only reason I move the app to the background for more than a few minutes is to save battery power.

**Comment by HarelM** [comment]
Bottom line: 
@valleyofdawn: Please update the initial comment and delete the above.
@zstadler: 3 and 4 are not clear, please open separate issues for them and link them here. or link the existing issues in the initial comment.

Other stuff:
>Other requests may come up once the above is implemented and further real-life testing the IHM app is done.

I was under the impression that most important issues are already open here in Github, if this is not the case I find it weird, please try and think with yourself why is that.
I believe you should know which features will allow you to move away from Orux - I'm not talking about bugs or stuff that require a better UX. If this is not the case, please sit down and map the features that you absolutely have that exist in Orux and open new issues here. It's not a contract, if all is implemented and you still can't leave Orux we should have another discussion not related to this one but an initial list that is not "Open" should exists to begin with, otherwise all I'll have is a failure feeling which I already have now, so why making an effort?

The following is vague and unhelpful, please try to avoid these kind of comments. If there's an open issue on it there's no need to repeat it.
>The offline map and measurement work well enough for me but would have to work better for production.

You have used 3 definitions for the same thing (measurement, record, and background tracking), which makes the reading your comment almost impossible.

In any case, there's no need to explain why recording is important to you, we all agree we need it, but as I said many times it is a very difficult problem, I hope to be able to make it work, I can't guarantee though, no need to repeat it, I got it.

**Comment by valleyofdawn** [comment]
I updated the list. By measurement I meant accumulated distance and height.

**Comment by HarelM** [comment]
I'm closing this discussion, the only issue left is being taken care of.
We can always open a new discussion about other issues and their priority.
