### ISSUE TITLE
Use `hike` vehicle for routing

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#1455]
## What I expect to happen
Routing for hikers should be able to go throuh paths with the followong `sac_scale` values: `alpine_hiking`, `demanding_alpine_hiking`, and `difficult_alpine_hiking`.

## What really happened
Currently, routing for hikers does not go through such paths.

## Things I think the developers should know, images, links etc.
- Graphhopper's `hike` vehicle seems to be better suited for our needs.
- For backward compatibility as well as eliminating the need for immediate update the web server, the `foot` profile would be temporarily redirected to the `hike` vehicle in addition to creating a new `hike` profile. At a later stage, the `foot` profile can be removed.

## Tasks
- [x] Change the `foot` profile in `graphhopper-docker` to use the `hike` vehicle
- [x] Add a `hike` profile to `graphhopper-docker`
- [x] Change the web server to use the `hike` profile
- [ ] Remove the `foot` profile

**Comment by HarelM** [comment]
Remove profile will be done after release - closing this issue and keeping a note about removal from the server
