### ISSUE TITLE
Record a route when the screen is off

### ISSUE THREAD

**Issue by HarelM** [IsraelHikingMap/Site#782]
## Feature
As a user I would like to be able to use IHM to record my routes.
The problem with current implementation is that when using the browser and the screen goes off the browser will be sent to the background and will stop recording.

In order to solve this using a different approach is needed - create a mobile app using [cordova](https://cordova.apache.org/).
The following might solve this:
https://github.com/mauron85/cordova-plugin-background-geolocation

Still to fix/implement:
### Critical  - for beta:
- [x] API Urls should be changed to IsraelHiking.osm.org.il
- [x] Translation files should be used from local location and not from site
- [x] Tiles should be used from IHM site and not locally
- [x] See if login is working as expected
- [x] Map should center GPS when it is on
- [x] When panning the map (`dragstart`), GPS icon should change and stop following, clicking on it will change the state back to "following"
- [x] Share URLs are incorrect.
- [x] Can't save to file - need [this plugin](https://www.neontribe.co.uk/cordova-file-plugin-examples/)
- [x] Add timestamp to site's data
- [x] When trying to edit the route while recording bad things happen - should create a route recording state that allows adding private POIs.
- [x] Save route when recording is finished - currently the route can vanish if the app goes to the background after recording is done. Alternatively, save after every some predefined interval.
- [x] App takes very long time to load.
- [x] Add confirmation dialog before closing the app. ~The following might allow this: https://stackoverflow.com/questions/276660/how-can-i-override-the-onbeforeunload-dialog-and-replace-it-with-my-own#answer-276739.    
[This stackexchange question](https://stackoverflow.com/questions/23409538/how-to-catch-exit-app-event) refers to a complicated exit/kill scenario, yet the author claims that "_I tried **onunload or onbeforeunload** but **these functions get called only if I close the app normally**, without minimizing it and closing it from task manager._" This is probably good enough for us.~ `onbeforeunload` doesn't work.
- [x] Overlays are missing
- [x] Use browser GPS alongside native - need to filter out if there are too many points close to eachother.
- [x] Fix adding of point from GPS - it always uses the first point by mistake

### Major - for production:
- [x] Update share didn't seem to work - need to verify.
- [x] Elevation is missing in the recording data - there's a question if to bring it when recording or just when saving.
- [x] Whatsapp share doesn't work
See here: https://cordova.apache.org/docs/en/latest/reference/cordova-plugin-whitelist/
- [x] Add initial location when the recording starts rather than the first location after a move
- [x] Adding a POI from GPS cursor fails the second time? need to verify.
- [x] Backbutton timeout to exit app should be more than 1 second.
- [ ] #799: Allow adding POI pictures directly from the device camera 
- [ ] #790: Button tooltips are not removed from screen after timeout - see here:
https://stackblitz.com/angular/jydgypqvqvk?file=app%2Ftooltip-modified-defaults-example.ts
- [x] Battery optimize popup - need [this plugin](https://github.com/thomas550i/cordova-plugin-doze-Optimize). - not sure it's working well: https://github.com/thomas550i/cordova-plugin-doze-Optimize/issues/1, it might be that we need this plugin and permission: https://github.com/NeoLSN/cordova-plugin-android-permissions/issues/19
Seems like non of the above will solve the problem, need to use a toast once.
- [x] When the application starts after an active recording was aborted, ask the user if he wants to continue the recording. If the answer is "no", continue as if the user just clicked "stop recording".
- [ ] #784: Allow "Open with ..." of `gpx` and `twl` files with the app

### Cool - not gating production:
- [x] ~Assign different actions to Android's "back" button~ moved to #796
- [x] Multiple recordings on the same day need to receive different names, preferably using start time. Currently, it is possible to change the properties of just one of them. 
- [ ] Choose a default color that will minimize conflict with the map colors. Purple seems like a good option - this currently use the route color mechanism, we might consider changing purple to be first.
- [x] When sharing the address is too long - need to break it - also we might consider using native share.
- [x] The text in the notification bar says that recording is active even when only GPS tracking is active.
- [ ] Allow cancel of GPS tracking when GPS has a hard time finding the location. - the code is there, not sure why it doesn't work...

**Comment by zstadler** [comment]
Interestingly, cordova has [support for SQLite storage](https://cordova.apache.org/docs/en/latest/cordova/storage/storage.html#sqlite-plugin) which can enable the use of OruxMaps offline maps (as a separate future issue).

The leaflet [MBTiles](https://gitlab.com/IvanSanchez/Leaflet.TileLayer.MBTiles) plugin has already implemented fetching tiles from an SQLite DB with a different scheme.

**Comment by HarelM** [comment]
@zstadler I moved offline tiles to a different issue - #783, I would like to remove your comment from this thread with your approval.

**Comment by HarelM** [comment]
I've used the browser platform of Cordova to test how the app will behave on a device that is not the current site and it seems that there are a few issues that needs to be fixed in order for this to properly work:
1. API Urls should be changed to IsraelHiking.osm.org.il - I still need to understand how to make this work when I want to debug this locally...
2. Translation files should be used from local location and not from site
3. Tiles should be used from IHM site and not locally - otherwise the app size will be 2Gb.
...

**Comment by HarelM** [comment]
The good news is that I manged to create an Android application that will run the site.
Issues that still remain:
1. Login fails due to the fact that it opens a new window when the user needs to login - not sure how to solve this, but I'll need to be creative.
2. All outside links seems not to work when testing on simulator - need to find a solution (In-App Browsing in the link above, I think)
3. Need to make sure that local storage is working and that current map location is saved between usages (Might be an issue with the emulator and not an actual thing).
4. Implementation of this feature.

**Comment by HarelM** [comment]
I have found a solution to the login using some of the code in the link below to open a window and add polling mechanism:
https://github.com/nraboy/ngx-cordova-oauth
I would like to change the "splash screen" to have some animation and remove the word "site" from it.
I hope I can make this in time before the holidays.

**Comment by HarelM** [comment]
Seems like the above plugin is not free, and not cheap, I'll see if the following plugin does the job:
https://github.com/mauron85/cordova-plugin-background-geolocation

**Comment by HarelM** [comment]
In order not to complicate this feature it will not solve offline issues (i.e. what happens if you try to share/upload a recording and you do not have internet connection).
Proposed UX (I will add images later):
1. After clicking the location button and GPS is in "tracking" mode a new button with red circle will be seen just below the GPS.
2. Clicking this button will start recording and the button will change to a black square.
3. When clicking the button again the recording will be finished and the recorded track will be saved as a new route layer.
4. Optionally - I haven't fully defined the UX here - the user will be able to upload the track to OSM, or the track will be uploaded automatically.
5. Clicking the GPS button again will do the same as clicking the stop button but will also disable tracking (as it does today).

Things to think about: The track name - do we want the user to give it when starting the recording or stopping it? or only when uploading to OSM or just use the date and allow the user to change it much like he can now with his routes.

**Comment by zstadler** [comment]
From the above description, it is not clear if a new layer is added when the recording starts or when it ends.

I prefer the layer to be added when the recording starts, and it becomes the active layer, as is the case with every new layer. This will enable the user to add private POIs to the layer while recording. The user will continue to be able to change the active layer regardless of the recording state.

I also suggest the layer will get an automatic name, as is today, rather than add a new dialog. The automatic name can be something like "Recording YYYY-MM-DD-HH-MM-SS" in English. This name can later be changed either manually or by changing it in the OSM upload dialog.

**Comment by HarelM** [comment]
Adding this as a layer when starting to record might be problematic as I don't think editing the recording should be available while recording and this create a layer that is not a regular one.
Regardless of the fact that this is layer will be seen in the layers control or not while recording the ability to add points to the recording is needed. It might be a second phase as I would like to fail fast in case this feature won't work as I need it to work.

**Comment by zstadler** [comment]
I agree that the first priority for the development is to determine the feasibility of the recording.

As long as this issue is also used for the UX of the feature, here are a few additional aspects:
- The recorded track is visible on the map.
- By default, the map is continuously centered on the GPS location.
- When recording is active, the user should be able to pan and zoom. 
- The user can modify the color, width and opacity of the recording. Ideally, this becomes the default for the next recording.
- When recording is active, the GPS button continues its function to toggle the centering of the map on the GPS location.
- After manual panning of the map, centering on the GPS location, if active, is suspended for 10/15 seconds, regardless of recording mode.

**Comment by HarelM** [comment]
> The user can modify the color, width and opacity of the recording. Ideally, this becomes the default for the next recording.

I don't think we should burden the user with it. If we ever get to create an elaborate advanced settings screen, this should be there, I don't think this should be part of this feature.

> When recording is active, the GPS button continues its function to toggle the centering of the map on the GPS location.

This is not intuitive, IMO, unless we change the icon to something else while recording, another option is to add another button for this.

> After manual panning of the map, centering on the GPS location, if active, is suspended for 10/15 seconds, regardless of recording mode.

This is a bit tricky - to start and map all the functionality that moves the map. I'm planning on implementing only manual panning to support this - meaning, for example, if a user searches for something and the map moves it will go back to GPS location unless the user started out with panning. I think it will cover most cases, since the context of the user when recording is usually to be around where he records.

I agree with the other requirements.

**Comment by HarelM** [comment]
BTW, as far as I can tell, Waze doesn't have a timeout, once you pan the map the search icon changes to "center-me". a good UX might be to unify the last two bullets @zstadler  wrote - once you pan, the GPS icon will change to something else and when you click on it, it will change to "centering" mode and center the map on the GPS location.

**Comment by zstadler** [comment]
There is already a "center-me" button which is inactive by default - we usually call it the "GPS" button". 
Regardless of the the recording feature, the user can activate and deactivate the "center-me" button at will.

The "center-me/GPS" button has an "active" indication (like the point and line editing buttons). I see no reason to involve the search button in this scenario. Simply deactivating the "center-me/GPS" button, when the user pans the map in recording mode, is perfectly fine. Actually, it makes sense that map panning by the user would deactivate the "center-me/GPS" button regardless of the recording mode.

**Comment by zstadler** [comment]
> > The user can modify the color, width and opacity of the recording. Ideally, this becomes the default for the next recording.

> I don't think we should burden the user with it. If we ever get to create an elaborate advanced settings screen, this should be there, I don't think this should be part of this feature.

Please consider the following scenario: the user activates the recording and randomly gets an poorly visible color, like yellow. She is stuck with this color for hours of recording time. Similarly, if the color is similar to other tracks and/or map trails color.

**Comment by HarelM** [comment]
>Please consider the following scenario:...

I'll take it into consideration although I never said recording color will be random. Most apps has a predefined color that doesn't change. I'm currently leaning toward using a regular route layer as suggested above so it should facilitate for this.

Initial testing of the code I added did not work :-/
I'll check how the following code is different from what I wrote, which is the official example of the library:
https://github.com/mauron85/cordova-plugin-background-geolocation-example/blob/4f6231ccdcd3531e80e48fa65a65037baee58b09/www/app.js

**Comment by HarelM** [comment]
It might be that the phone is killing the app due to doze mode, need to manually change it in phone settings to see if it solves, if so - add the following plugin:
ordova plugin add https://github.com/thomas550i/cordova-plugin-doze-Optimize

**Comment by HarelM** [comment]
Relevant issue opened in the plugin repository:
https://github.com/mauron85/cordova-plugin-background-geolocation/issues/470

**Comment by zstadler** [comment]
Additional points:

10. Multiple recordings on the same day need to receive different names, preferably using start time. Currently, it is possible to change the properties of just one of them. 

11. Choose a default color that will minimize conflict with the map colors. Purple seems like a good option.

**Comment by HarelM** [comment]
@valleyofdawn can you create an icon for "return to following GPS mode" that I can place on the GPS button when the user pans the map and "breaks" GPS following mode?
I thought about something like 4 arrows pointing to the center and maybe a dot in the center.

**Comment by valleyofdawn** [comment]
SVG?

**Comment by HarelM** [comment]
Yup.

**Comment by valleyofdawn** [comment]
[converge.svg.txt](https://github.com/IsraelHikingMap/Site/files/2321363/converge.svg.txt)

**Comment by zstadler** [comment]
I have encountered situations where background recording has stopped. The notification icon was present, but when it was clicked, the application simply restarted.
Since the recording was not saved, it is hard to know where it happened and, for example, if it was a result of a GPS signal loss.

**Comment by zstadler** [comment]
I'm sure about the power settings, but not about the GPS reception and potential touch of the "back" button that closed the application.

Please consider implementing the track saving and the exit confirmation dialog so I can further investigate this behavior.

**Comment by HarelM** [comment]
Proposed saved local routes UX (this will probably won't make it fully to this release as I think it should be handled as part of #777):
1. Once the recording is finished - the route should be added to the local routes list
2. Local routes list will be another tab/dialog under the user profile.
3. The following action can be done on local route:
3.1 Upload to OSM
3.2 Show on map
3.3 Delete
3.4 Rename?
4. Once uploaded to OSM it will be removed from this list.
5. I think that when entering user profile local routes should be uploaded to OSM if possible to reduce data lose etc, local routes is just a simple mechanism to temporary store the data.
Ideas and thoughts are welcome.

**Comment by zstadler** [comment]
An alternative UX is
1. Recordings are saved to local storage. 
2. All local recordings are shown as Private Routes layers
3. The existing route properties dialog allows rename, deletion and other actions
4. Add "Upload to OSM" in the route properties dialog for logged-in users

Pros:
- Simple
- Recordings are visible and easily accessible
- Encourage users to minimize the use of local storage for 10's or 100's of recordings
- Less development effort by reusing existing UI

**Comment by zstadler** [comment]
For both proposals, I think a recording should not be done automatically after an upload to OSM.

After an upload,  a person may want to save the recording as GPX, share it, keep the recording for a while, etc.

**Comment by HarelM** [comment]
Camera related SO questions:
https://stackoverflow.com/questions/35090461/using-camera-on-phonegap-app-with-only-html-input-without-camera-api
https://stackoverflow.com/questions/26381050/choose-camera-in-file-upload-in-cordova-application-on-android-without-using-cor
https://stackoverflow.com/questions/21523544/html-file-input-control-with-capture-and-accept-attributes-works-wrong

Seems like this is an annoying issue.
Some possible solutions that needs to be tested:
1. Use crosswalk?
https://crosswalk-project.org/documentation/cordova.html
2.  add all the following plug-ins:
 * cordova-plugin-camera
 * cordova-plugin-media-capture
 * cordova-plugin-device
 * cordova-plugin-file
 * cordova-plugin-media
3. 1+2?

**Comment by HarelM** [comment]
This was implemented and released to beta.
Closing.
Please use Github tags to address beta exit issues by defining their priority as high + cordova.
